from __future__ import annotations

from ...ui_contract.api import UiNode
from ...ui_contract.api import UiTree


def web_settings_ui_tree() -> UiTree:
    return UiTree(
        frontend="web",
        view="settings",
        root_id="settings.dialog",
        nodes=(
            UiNode("settings.dialog", "dialog", children=("settings.tabs",), layout="window", visible=True),
            UiNode(
                "settings.tabs",
                "tabs",
                children=(
                    "settings.general",
                    "settings.dictionary",
                    "settings.mcp",
                    "settings.updates",
                    "settings.profiling",
                ),
                widget="tabs",
            ),
            UiNode(
                "settings.general",
                "tab",
                children=(
                    "settings.text_font_size",
                    "settings.button_font_size",
                    "settings.theme",
                    "settings.language",
                    "settings.default_agent",
                    "settings.system_prompt",
                    "settings.bash_output",
                    "settings.codex_model",
                    "settings.codex_reasoning",
                    "settings.codex_animations_enabled",
                    "settings.claude_model",
                    "settings.claude_effort",
                    "settings.claude_animations_enabled",
                ),
                label_key="settings_dictionary_general",
                layout="grid",
            ),
            _number("settings.text_font_size", "text_font_size", 8, 28, 1),
            _number("settings.button_font_size", "button_font_size", 8, 28, 1),
            UiNode("settings.theme", "field", label_key="theme", widget="select"),
            UiNode("settings.language", "field", label_key="language", widget="select"),
            UiNode("settings.default_agent", "field", label_key="default_agent", widget="select"),
            UiNode(
                "settings.system_prompt",
                "field",
                label_key="system_prompt",
                widget="text_area",
                height=96,
                hexpand=True,
                vexpand=False,
            ),
            UiNode(
                "settings.bash_output",
                "section",
                children=(
                    "settings.limited_bash_head_tokens",
                    "settings.limited_bash_tail_tokens",
                    "settings.limited_bash_heartbeat_seconds",
                    "settings.limited_bash_heartbeat_tokens",
                ),
                label_key="settings_section_bash_output",
                layout="grid",
            ),
            _number("settings.limited_bash_head_tokens", "limited_bash_head_tokens", 100, 200_000, 100),
            _number("settings.limited_bash_tail_tokens", "limited_bash_tail_tokens", 100, 200_000, 100),
            _number("settings.limited_bash_heartbeat_seconds", "limited_bash_heartbeat_seconds", 1, 300, 1),
            _number("settings.limited_bash_heartbeat_tokens", "limited_bash_heartbeat_tokens", 0, 200_000, 100),
            UiNode("settings.codex_model", "field", label_key="default_codex_model", widget="select"),
            UiNode("settings.codex_reasoning", "field", label_key="default_codex_reasoning", widget="select"),
            UiNode(
                "settings.codex_animations_enabled",
                "field",
                label_key="codex_animations_enabled",
                widget="checkbox",
            ),
            UiNode("settings.claude_model", "field", label_key="default_claude_model", widget="select"),
            UiNode("settings.claude_effort", "field", label_key="default_claude_effort", widget="select"),
            UiNode(
                "settings.claude_animations_enabled",
                "field",
                label_key="claude_animations_enabled",
                widget="checkbox",
            ),
            UiNode(
                "settings.dictionary",
                "tab",
                children=(
                    "settings.dictionary_auto_discovery",
                    "settings.dictionary_strip_articles",
                    "settings.dictionary_min_occurrences",
                    "settings.dictionary_min_saving",
                    "settings.dictionary_min_term_length",
                    "settings.dictionary_max_term_words",
                    "settings.dictionary_preview_text",
                ),
                label_key="settings_dictionary_dictionary",
                layout="grid",
            ),
            UiNode(
                "settings.dictionary_auto_discovery",
                "field",
                label_key="settings_dictionary_auto_discover",
                widget="checkbox",
            ),
            UiNode(
                "settings.dictionary_strip_articles",
                "field",
                label_key="settings_dictionary_strip_articles",
                widget="checkbox",
            ),
            _number("settings.dictionary_min_occurrences", "settings_dictionary_min_occurrences", 1, 20, 1),
            _number("settings.dictionary_min_saving", "settings_dictionary_min_saving", 0, 10_000, 1),
            _number("settings.dictionary_min_term_length", "settings_dictionary_min_term_length", 1, 200, 1),
            _number("settings.dictionary_max_term_words", "settings_dictionary_max_term_words", 1, 20, 1),
            UiNode(
                "settings.dictionary_preview_text",
                "field",
                label_key="settings_dictionary_preview_text",
                widget="text_area",
                hexpand=True,
                vexpand=True,
            ),
            UiNode(
                "settings.mcp",
                "tab",
                children=(
                    "settings.mcp_trusted",
                    "settings.mcp_group_search",
                    "settings.mcp_group_python",
                    "settings.mcp_group_task_context",
                    "settings.mcp_group_task_actions",
                    "settings.mcp_group_commit_messages",
                    "settings.mcp_group_validation",
                    "settings.mcp_group_repo_guard",
                    "settings.mcp_group_paf",
                    "settings.mcp_group_paf_env",
                    "settings.mcp_group_yocto",
                ),
                label_key="settings_mcp",
                layout="vertical",
            ),
            UiNode("settings.mcp_trusted", "field", label_key="settings_mcp_trusted", widget="checkbox"),
            UiNode("settings.mcp_group_search", "field", label_key="settings_mcp_group_search", widget="checkbox"),
            UiNode("settings.mcp_group_python", "field", label_key="settings_mcp_group_python", widget="checkbox"),
            UiNode(
                "settings.mcp_group_task_context",
                "field",
                label_key="settings_mcp_group_task_context",
                widget="checkbox",
            ),
            UiNode(
                "settings.mcp_group_task_actions",
                "field",
                label_key="settings_mcp_group_task_actions",
                widget="checkbox",
            ),
            UiNode(
                "settings.mcp_group_commit_messages",
                "field",
                label_key="settings_mcp_group_commit_messages",
                widget="checkbox",
            ),
            UiNode("settings.mcp_group_validation", "field", label_key="settings_mcp_group_validation", widget="checkbox"),
            UiNode("settings.mcp_group_repo_guard", "field", label_key="settings_mcp_group_repo_guard", widget="checkbox"),
            UiNode("settings.mcp_group_paf", "field", label_key="settings_mcp_group_paf", widget="checkbox"),
            UiNode("settings.mcp_group_paf_env", "field", label_key="settings_mcp_group_paf_env", widget="checkbox"),
            UiNode("settings.mcp_group_yocto", "field", label_key="settings_mcp_group_yocto", widget="checkbox"),
            UiNode(
                "settings.updates",
                "tab",
                children=(
                    "settings.check_updates",
                    "settings.apply_update",
                    "settings.update_status",
                ),
                label_key="settings_updates",
                layout="vertical",
            ),
            UiNode("settings.check_updates", "action", label_key="settings_check_updates", widget="button"),
            UiNode("settings.apply_update", "action", label_key="settings_apply_update", widget="button"),
            UiNode("settings.update_status", "status", label_key="settings_update_idle", widget="text"),
            UiNode(
                "settings.profiling",
                "tab",
                children=(
                    "settings.profiling_enabled",
                    "settings.profiling_clear",
                    "settings.profiling_crash_dump",
                    "settings.profiling_note",
                    "settings.profiling_output",
                ),
                label_key="settings_profiling",
                layout="vertical",
            ),
            UiNode(
                "settings.profiling_enabled",
                "field",
                label_key="settings_profiling_enable",
                widget="checkbox",
            ),
            UiNode("settings.profiling_clear", "action", label_key="settings_profiling_clear", widget="button"),
            UiNode(
                "settings.profiling_crash_dump",
                "action",
                label_key="settings_profiling_crash_dump",
                widget="button",
            ),
            UiNode("settings.profiling_note", "text", label_key="settings_profiling_note", widget="text"),
            UiNode("settings.profiling_output", "text", widget="text_area", hexpand=True, vexpand=True),
        ),
    )


def _number(node_id: str, label_key: str, minimum: int, maximum: int, step: int) -> UiNode:
    return UiNode(
        node_id,
        "field",
        label_key=label_key,
        widget="number",
        min_value=minimum,
        max_value=maximum,
        step=step,
    )
