from __future__ import annotations


def theme_colors(theme: str) -> dict[str, str]:
    if theme == "dark":
        return {
            "background": "#202124",
            "codex_running_background": "#26384d",
            "codex_running_border": "#7aa2f7",
            "codex_running_foreground": "#ffffff",
            "codex_running_glow": "rgba(122, 162, 247, 0.75)",
            "agent_session_background": "#4b3713",
            "agent_session_foreground": "#ffe6a3",
            "agent_external_background": "#34383d",
            "agent_external_foreground": "#a8b0ba",
            "text_background": "#111315",
            "terminal_background": "#111315",
            "control_background": "#2b2f33",
            "control_hover_background": "#343a40",
            "titlebar_background": "#16191d",
            "tab_background": "#202124",
            "tab_selected_background": "#111315",
            "tab_selected_foreground": "#f5f7fa",
            "muted_foreground": "#a8b0ba",
            "selection_background": "#3f6f9f",
            "selection_foreground": "#ffffff",
            "menu_background": "#252a2f",
            "border": "#4a5058",
            "separator": "#6a727c",
            "foreground": "#e8eaed",
        }
    return {
        "background": "#f2f2f2",
        "codex_running_background": "#d9e7ff",
        "codex_running_border": "#2f6fbb",
        "codex_running_foreground": "#14345f",
        "codex_running_glow": "rgba(47, 111, 187, 0.45)",
        "agent_session_background": "#fff1c2",
        "agent_session_foreground": "#5c3b00",
        "agent_external_background": "#e0e0e0",
        "agent_external_foreground": "#5f6368",
        "text_background": "#ffffff",
        "terminal_background": "#ffffff",
        "control_background": "#f8f8f8",
        "control_hover_background": "#ffffff",
        "titlebar_background": "#ededed",
        "tab_background": "#e8e8e8",
        "tab_selected_background": "#ffffff",
        "tab_selected_foreground": "#202124",
        "muted_foreground": "#5f6368",
        "selection_background": "#2f6fbb",
        "selection_foreground": "#ffffff",
        "menu_background": "#ffffff",
        "border": "#b8b8b8",
        "separator": "#8c8c8c",
        "foreground": "#202124",
    }
