CONFIG_XEN_HARNESS=y
CONFIG_XEN_HARNESS_DOMU_CONSOLE_COLLECTOR=y
CONFIG_XEN_HARNESS_DOMU_AUTOSTART=y
CONFIG_XEN_HARNESS_DOMU_AUTOSTART_DOMID=0
CONFIG_XEN_LIBFDT=y
CONFIG_XEN_DOMCTL_INTERFACE_VERSION=0x17
CONFIG_XEN_SYSCTL_INTERFACE_VERSION=0x15
CONFIG_HEAP_MEM_POOL_SIZE=262144
