from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import yaml


GENERATED_NOTICE = "GENERATED by agent_tools/tools/rules_sync -- DO NOT EDIT BY HAND"
CLAUDE_BEGIN = "<!-- BEGIN GENERATED agent_tools/tools/rules_sync: always-rules -->"
CLAUDE_END = "<!-- END GENERATED agent_tools/tools/rules_sync -->"
CLAUDE_MARKER_RE = re.compile(
    re.escape(CLAUDE_BEGIN) + r".*?" + re.escape(CLAUDE_END),
    re.DOTALL,
)
FRONTMATTER_RE = re.compile(r"\A---\r?\n(.*?\r?\n)---\r?\n", re.DOTALL)
CODEX_WORD_RE = re.compile(r"\bCodex\b")


class RulesSyncError(RuntimeError):
    pass


def find_project_root(start: Path) -> Path:
    for candidate in (start.resolve(), *start.resolve().parents):
        if (candidate / "AGENTS.md").is_file() and (candidate / "agent_tools").is_dir():
            return candidate
    raise RulesSyncError(
        "could not locate workspace root: no ancestor of "
        f"{start} has both AGENTS.md and agent_tools/"
    )


@dataclass(frozen=True)
class RuleFile:
    rel_path: str
    frontmatter: dict
    body: str

    @property
    def sync_mode(self) -> str:
        mode = self.frontmatter.get("sync")
        if mode not in ("always", "skill", "none"):
            raise RulesSyncError(
                f"{self.rel_path}: missing or invalid `sync:` frontmatter "
                "(expected always, skill, or none)"
            )
        return mode

    @property
    def slug(self) -> str:
        return Path(self.rel_path).stem

    @property
    def title(self) -> str:
        for line in self.body.splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                return stripped[2:].strip()
        return self.slug

    @property
    def scope_sentence(self) -> str:
        lines = self.body.splitlines()
        paragraph: list[str] = []
        seen_title = False
        for line in lines:
            stripped = line.strip()
            if not seen_title:
                if stripped.startswith("# "):
                    seen_title = True
                continue
            if not stripped:
                if paragraph:
                    break
                continue
            paragraph.append(stripped)
        return " ".join(paragraph).strip()


@dataclass(frozen=True)
class SkillFile:
    rel_path: str
    frontmatter: dict
    body: str

    @property
    def name(self) -> str:
        name = self.frontmatter.get("name")
        if not name:
            raise RulesSyncError(f"{self.rel_path}: SKILL.md frontmatter is missing `name:`")
        return str(name)

    @property
    def rule_backref(self) -> str | None:
        rule = self.frontmatter.get("rule")
        return str(rule) if rule else None


def _split_frontmatter(text: str) -> tuple[dict, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    raw = match.group(1)
    data = yaml.safe_load(raw) or {}
    if not isinstance(data, dict):
        raise RulesSyncError("frontmatter block must decode to a mapping")
    return data, text[match.end():]


def discover_rules(root: Path) -> list[RuleFile]:
    rules_dir = root / "agent_tools" / "rules"
    rules = []
    for path in sorted(rules_dir.rglob("*.md")):
        frontmatter, body = _split_frontmatter(path.read_text(encoding="utf-8"))
        rules.append(RuleFile(rel_path=str(path.relative_to(root)), frontmatter=frontmatter, body=body))
    return rules


def discover_skills(root: Path) -> list[SkillFile]:
    skills_dir = root / "agent_tools" / "skills"
    skills = []
    for path in sorted(skills_dir.glob("*/SKILL.md")):
        frontmatter, body = _split_frontmatter(path.read_text(encoding="utf-8"))
        skills.append(SkillFile(rel_path=str(path.relative_to(root)), frontmatter=frontmatter, body=body))
    return skills


def _neutralize_codex_wording(text: str) -> str:
    return CODEX_WORD_RE.sub("the agent", text)


def _mirrored_skill_frontmatter(skill: SkillFile) -> dict:
    data = {key: value for key, value in skill.frontmatter.items() if key != "rule"}
    if "description" in data:
        data["description"] = _neutralize_codex_wording(str(data["description"]))
    return data


def _render_skill_file(frontmatter: dict, body: str, source_rel_path: str) -> str:
    front_text = yaml.safe_dump(frontmatter, default_flow_style=False, sort_keys=False).strip()
    notice = f"<!-- {GENERATED_NOTICE}. Source: {source_rel_path} -->"
    return f"---\n{front_text}\n---\n\n{notice}\n\n{body.lstrip()}"


def _mirror_skill(skill: SkillFile) -> tuple[str, str]:
    frontmatter = _mirrored_skill_frontmatter(skill)
    body = _neutralize_codex_wording(skill.body)
    content = _render_skill_file(frontmatter, body, skill.rel_path)
    return skill.name, content


def _stub_skill_for_rule(rule: RuleFile) -> tuple[str, str]:
    description = rule.scope_sentence or rule.title
    frontmatter = {
        "name": rule.slug,
        "description": (
            f"{description} Authoritative source: `{rule.rel_path}`. "
            "This skill is an auto-generated stub; read the rule file in full "
            "before acting on it."
        ),
    }
    body = (
        f"# {rule.title}\n\n"
        f"Follow `{rule.rel_path}` for the authoritative policy. Read that file "
        "in full before acting; this stub only routes to it and does not "
        "duplicate its content.\n"
    )
    content = _render_skill_file(frontmatter, body, rule.rel_path)
    return rule.slug, content


def plan_skill_outputs(root: Path, rules: list[RuleFile], skills: list[SkillFile]) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    claude_skills_dir = root / ".claude" / "skills"

    rules_covered_by_skill: set[str] = set()
    for skill in skills:
        name, content = _mirror_skill(skill)
        outputs[claude_skills_dir / name / "SKILL.md"] = content
        if skill.rule_backref:
            rules_covered_by_skill.add(skill.rule_backref)

    for rule in rules:
        if rule.sync_mode != "skill":
            continue
        if rule.rel_path in rules_covered_by_skill:
            continue
        name, content = _stub_skill_for_rule(rule)
        outputs[claude_skills_dir / name / "SKILL.md"] = content

    return outputs


def _demote_heading(body: str) -> str:
    lines = body.lstrip("\n").splitlines()
    if lines and lines[0].startswith("# "):
        lines[0] = "#" + lines[0]
    return "\n".join(lines).rstrip() + "\n"


def render_claude_always_block(rules: list[RuleFile]) -> str:
    sections = []
    for rule in sorted((r for r in rules if r.sync_mode == "always"), key=lambda r: r.rel_path):
        sections.append(
            f"<!-- Source: {rule.rel_path} -->\n\n{_demote_heading(rule.body)}"
        )
    joined = "\n".join(sections).rstrip()
    return f"{CLAUDE_BEGIN}\n\n{joined}\n\n{CLAUDE_END}"


def plan_claude_md(root: Path, rules: list[RuleFile]) -> Path | None:
    claude_md = root / "CLAUDE.md"
    if not claude_md.is_file():
        return None
    text = claude_md.read_text(encoding="utf-8")
    block = render_claude_always_block(rules)
    if CLAUDE_MARKER_RE.search(text):
        new_text = CLAUDE_MARKER_RE.sub(lambda _m: block, text)
    else:
        separator = "" if text.endswith("\n") else "\n"
        new_text = f"{text}{separator}\n{block}\n"
    return claude_md, new_text


def plan_all(root: Path) -> dict[Path, str]:
    rules = discover_rules(root)
    skills = discover_skills(root)
    outputs = plan_skill_outputs(root, rules, skills)
    claude_plan = plan_claude_md(root, rules)
    if claude_plan is not None:
        path, content = claude_plan
        outputs[path] = content
    return outputs


@dataclass(frozen=True)
class SyncResult:
    changed: list[Path]
    unchanged: list[Path]

    @property
    def is_clean(self) -> bool:
        return not self.changed


def apply_plan(outputs: dict[Path, str], *, check_only: bool) -> SyncResult:
    changed = []
    unchanged = []
    for path, content in sorted(outputs.items()):
        existing = path.read_text(encoding="utf-8") if path.is_file() else None
        if existing == content:
            unchanged.append(path)
            continue
        changed.append(path)
        if not check_only:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return SyncResult(changed=changed, unchanged=unchanged)
