BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xen-harness"
BBFILE_PATTERN_xen-harness = "^${LAYERDIR}/"
BBFILE_PRIORITY_xen-harness = "7"

LAYERSERIES_COMPAT_xen-harness = "kirkstone"
